#ifndef OPENDRIVEROADOBJECTOUTLINECORNERROAD_HPP
#define OPENDRIVEROADOBJECTOUTLINECORNERROAD_HPP


class OpenDriveRoadObjectOutlineCornerRoad
{
public:
  OpenDriveRoadObjectOutlineCornerRoad();
};

#endif // OPENDRIVEROADOBJECTOUTLINECORNERROAD_HPP
