#ifndef OPENDRIVEROADLANELINKPREDECESSOR_HPP
#define OPENDRIVEROADLANELINKPREDECESSOR_HPP


class OpenDriveRoadLaneLinkPredecessor
{
public:
  OpenDriveRoadLaneLinkPredecessor();
};

#endif // OPENDRIVEROADLANELINKPREDECESSOR_HPP
