#ifndef OPENDRIVEJUNCTIONCONNECTIONLANELINK_HPP
#define OPENDRIVEJUNCTIONCONNECTIONLANELINK_HPP


class OpenDriveJunctionConnectionLaneLink
{
public:
  OpenDriveJunctionConnectionLaneLink();
};

#endif // OPENDRIVEJUNCTIONCONNECTIONLANELINK_HPP
