#ifndef OPENDRIVEROADOBJECTPARKINGSPACEMARKING_HPP
#define OPENDRIVEROADOBJECTPARKINGSPACEMARKING_HPP


class OpenDriveRoadObjectParkingSpaceMarking
{
public:
  OpenDriveRoadObjectParkingSpaceMarking();
};

#endif // OPENDRIVEROADOBJECTPARKINGSPACEMARKING_HPP
